name: gboard_enhancer_lsp
description: Flutter UI + Kotlin LSPosed core for Gboard Enhancer.
publish_to: 'none'
version: 0.2.0-dev+2

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
